# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'operationsGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class OperForm(QtWidgets.QWidget):
    def setupUi(self):
        self.resize(775, 589)
        self.label = QtWidgets.QLabel('GEE Layer')
        self.label.setGeometry(QtCore.QRect(40, 20, 61, 16))
		
        self.geeLayer = QtWidgets.QComboBox()
        self.geeLayer.setGeometry(QtCore.QRect(100, 20, 131, 22))
		
        self.vectorLayer = QtWidgets.QComboBox()
        self.vectorLayer.setGeometry(QtCore.QRect(340, 20, 131, 22))
        self.vectorLayer.setEditable(True)
        self.vectorLayer.setMinimumWidth(130)
		
        self.label_2 = QtWidgets.QLabel('Vector Layer')
        self.label_2.setGeometry(QtCore.QRect(270, 20, 61, 16))
		
        self.useSelected = QtWidgets.QCheckBox()
        self.useSelected.setGeometry(QtCore.QRect(330, 60, 161, 17))
        self.useSelected.setText('use only selected features')
		
        self.label_11 = QtWidgets.QLabel('Layer name')
        self.label_11.setGeometry(QtCore.QRect(60, 60, 61, 16))
		
        self.layer_name = QtWidgets.QLineEdit()
        self.layer_name.setGeometry(QtCore.QRect(120, 60, 113, 20))
		
        self.clipWarning = QtWidgets.QLabel('No features selected in current  layer')
        self.clipWarning.setGeometry(QtCore.QRect(340, 70, 480, 28))
        self.clipWarning.setStyleSheet("color: \'red\';")
		
        self.form_1 = QtWidgets.QFormLayout()
        self.form_1.addRow(self.label, self.geeLayer)
        self.form_1.addRow(self.label_11, self.layer_name)
		
        self.form_2 = QtWidgets.QFormLayout()
        self.form_2.addRow(self.label_2, self.vectorLayer)
        self.form_2.addRow(self.useSelected)
		
        self.formsH = QtWidgets.QHBoxLayout()
        self.formsH.addLayout(self.form_1)
        self.formsH.addSpacing(50)
        self.formsH.addLayout(self.form_2)
        self.formsH.setContentsMargins(5,5,5,5)
		
        self.painting = QgsCollapsibleGroupBox()
        self.painting.setGeometry(QtCore.QRect(40, 185, 429, 180))
        self.painting.setMinimumSize(QtCore.QSize(0, 0))
        self.painting.setMaximumSize(QtCore.QSize(480, 180))
        self.painting.setCollapsed(False)
        self.painting.setSaveCollapsedState(False)
        self.painting.setTitle('Painting')
		
        self.paintButton = QtWidgets.QPushButton('paint layer', self.painting)
        self.paintButton.setGeometry(QtCore.QRect(320, 60, 75, 31))
		
        self.horizontalSlider = QtWidgets.QSlider(self.painting)
        self.horizontalSlider.setGeometry(QtCore.QRect(70, 60, 131, 21))
        self.horizontalSlider.setProperty("value", 99)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
		
        self.label_5 = QtWidgets.QLabel('Opacity', self.painting)
        self.label_5.setGeometry(QtCore.QRect(20, 60, 47, 21))

        self.label_8 = QtWidgets.QLabel('Palette', self.painting)
        self.label_8.setGeometry(QtCore.QRect(20, 110, 47, 13))
		
        self.palette = QtWidgets.QLineEdit(self.painting)
        self.palette.setGeometry(QtCore.QRect(80, 110, 91, 20))

        self.property = QtWidgets.QLineEdit(self.painting)
        self.property.setGeometry(QtCore.QRect(260, 110, 91, 20))
		
        self.label_9 = QtWidgets.QLabel('Min', self.painting)
        self.label_9.setGeometry(QtCore.QRect(50, 150, 47, 13))
		
        self.minBox = QtWidgets.QSpinBox(self.painting)
        self.minBox.setGeometry(QtCore.QRect(80, 150, 91, 22))
        self.minBox.setMinimum(-50000)
        self.minBox.setMaximum(50000)
        self.minBox.setSingleStep(100)
		
        self.label_12 = QtWidgets.QLabel('Property',self.painting)
        self.label_12.setGeometry(QtCore.QRect(200, 110, 47, 13))
		
        self.label_10 = QtWidgets.QLabel('Max', self.painting)
        self.label_10.setGeometry(QtCore.QRect(216, 150, 31, 20))
		
        self.maxBox = QtWidgets.QSpinBox(self.painting)
        self.maxBox.setGeometry(QtCore.QRect(260, 150, 91, 22))
        self.maxBox.setMinimum(-50000)
        self.maxBox.setMaximum(50000)
        self.maxBox.setSingleStep(100)
		
        self.paintRadio = QtWidgets.QRadioButton(self.painting)
        self.paintRadio.setGeometry(QtCore.QRect(70, 20, 60, 17))
        self.paintRadio.setText('paint')
		
        self.blendRadio = QtWidgets.QRadioButton(self.painting)
        self.blendRadio.setGeometry(QtCore.QRect(130, 20, 60, 17))
        self.blendRadio.setChecked(True)
        self.blendRadio.setText('blend')
		
        self.opaqueRadio = QtWidgets.QRadioButton(self.painting)
        self.opaqueRadio.setGeometry(QtCore.QRect(340, 20, 60, 17))
        self.opaqueRadio.setText('opaque')
		
        self.strokeRadio = QtWidgets.QRadioButton(self.painting)
        self.strokeRadio.setGeometry(QtCore.QRect(280, 20, 60, 17))
        self.strokeRadio.setChecked(False)
        self.strokeRadio.setText('stroke')
		
		
        self.reducing = QgsCollapsibleGroupBox()
        self.reducing.setGeometry(QtCore.QRect(40, 375, 429, 180))
        self.reducing.setMinimumSize(QtCore.QSize(0, 0))
        self.reducing.setMaximumSize(QtCore.QSize(480, 180))
        self.reducing.setCollapsed(False)
        self.reducing.setSaveCollapsedState(False)
        self.reducing.setTitle('Reducing')
		
        self.kernelType = QtWidgets.QComboBox(self.reducing)
        self.kernelType.setGeometry(QtCore.QRect(270, 115, 101, 22))
        self.kernelType.addItems(['circle', 'cross', 'diamond', 'octagon', 'plus', 'square'])

        self.scaleBox = QtWidgets.QSpinBox(self.reducing)
        self.scaleBox.setGeometry(QtCore.QRect(90, 110, 81, 22))
        self.scaleBox.setMaximum(5000)
        self.scaleBox.setProperty("value", 1000)

        self.label_7 = QtWidgets.QLabel('Type', self.reducing)
        self.label_7.setGeometry(QtCore.QRect(60, 60, 47, 16))

        self.label_16 = QtWidgets.QLabel('Radius', self.reducing)
        self.label_16.setGeometry(QtCore.QRect(210, 150, 47, 13))

        self.label_13 = QtWidgets.QLabel('Scale', self.reducing)
        self.label_13.setGeometry(QtCore.QRect(50, 110, 31, 21))

        self.label_14 = QtWidgets.QLabel('Max Pixels', self.reducing)
        self.label_14.setGeometry(QtCore.QRect(30, 150, 51, 21))

        self.kernelRadius = QtWidgets.QSpinBox(self.reducing)
        self.kernelRadius.setGeometry(QtCore.QRect(270, 145, 61, 22))
        self.kernelRadius.setMinimum(1)
        self.kernelRadius.setMaximum(1000)
        self.kernelRadius.setProperty("value", 3)

        self.pixBox = QtWidgets.QSpinBox(self.reducing)
        self.pixBox.setGeometry(QtCore.QRect(90, 150, 61, 22))
        self.pixBox.setProperty("value", 10)

        self.neighborhood = QtWidgets.QRadioButton(self.reducing)
        self.neighborhood.setGeometry(QtCore.QRect(290, 20, 91, 17))
        self.neighborhood.setText('neighborhood')

        self.label_15 = QtWidgets.QLabel('Kernel', self.reducing)
        self.label_15.setGeometry(QtCore.QRect(210, 110, 47, 21))

        self.region = QtWidgets.QRadioButton(self.reducing)
        self.region.setGeometry(QtCore.QRect(211, 19, 81, 20))
        self.region.setText('region')

        self.label_17 = QtWidgets.QLabel('px', self.reducing)
        self.label_17.setGeometry(QtCore.QRect(340, 150, 47, 16))

        self.bandsRadio = QtWidgets.QRadioButton(self.reducing)
        self.bandsRadio.setGeometry(QtCore.QRect(100, 20, 90, 17))
        self.bandsRadio.setText('bands/images')

        self.typeBox = QtWidgets.QComboBox(self.reducing)
        self.typeBox.setGeometry(QtCore.QRect(90, 61, 131, 22))
        self.typeBox.addItems(['count','first', 'last','max','mean','median','min','stdDev','sum','variance'])
        self.typeBox.setCurrentText("count")

        self.reduceButton = QtWidgets.QPushButton('reduce', self.reducing)
        self.reduceButton.setGeometry(QtCore.QRect(320, 60, 75, 31))

		
        self.clipping = QgsCollapsibleGroupBox()
        self.clipping.setEnabled(True)
        self.clipping.setGeometry(QtCore.QRect(40, 115, 200, 60))
        self.clipping.setMinimumSize(QtCore.QSize(0, 0))
        self.clipping.setMaximumSize(QtCore.QSize(200, 60))
        self.clipping.setCollapsed(False)
        self.clipping.setScrollOnExpand(False)
        self.clipping.setSaveCollapsedState(False)
        self.clipping.setTitle('Clipping')

        self.clipCollection = QtWidgets.QPushButton('clip', self.clipping)
        self.clipCollection.setGeometry(QtCore.QRect(50, 25, 75, 31))
		
		
        self.panelsV = QtWidgets.QVBoxLayout()
        self.panelsV.addWidget(self.clipping)
        self.panelsV.addWidget(self.painting)
        self.panelsV.addWidget(self.reducing)
		
        self.mainLayout = QtWidgets.QVBoxLayout()
        self.mainLayout.addLayout(self.formsH)
        self.mainLayout.addWidget(self.clipWarning, alignment=QtCore.Qt.AlignCenter)
        self.mainLayout.addLayout(self.panelsV)
        self.mainLayout.addStretch()
        self.mainLayout.setSpacing(5)
		
        self.setLayout(self.mainLayout)


from qgscollapsiblegroupbox import QgsCollapsibleGroupBox
